name = "test_package"
uuid = "9379ae98-f98a-4e49-b479-a11d9baa9608"
authors = ["pzebrowsk <zebrowsk@iiasa.ac.at> and contributors"]
version = "1.0.0-DEV"

[deps]
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
